### ISSUE TITLE
UWP runtime broken

### ISSUE THREAD

**Issue by UdaraAlwis** [BaseflowIT/Chameleon#104]
## 🐛 Bug Report

UWP run time throws an exception and breaks the app on start up.

![image](https://user-images.githubusercontent.com/1930490/84923814-48540580-b0fa-11ea-8568-90b91bc16014.png)

### Expected behavior
UWP App should build and run without any exception locally on Visual Studio

### Reproduction steps
Step 1: Open the solution in Visual studio 2019 on Windows 10
Step 2: Build the UWP project and run
Step 3: App breaks on start up with the following exception:
'CrossMediaManager.Current' threw an exception of type 'System.NotImplementedException'

**Full exception log:**
```
Exception thrown: 'System.NotImplementedException' in MediaManager.dll
An exception of type 'System.NotImplementedException' occurred in MediaManager.dll but was not handled in user code
This functionality is not implemented in the portable version of this assembly. You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
```
### Configuration

**Version:** 
Chameleon version 1.0.0.0 - develop branch
Plugin.MediaManager.Forms version 0.9.7

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
The minimum version needs to be updated. Can you open a PR?

**Comment by UdaraAlwis** [comment]
Updated the version numbers, but I'm not sure how to open a PR without having a fix. :( any suggestions?

**Comment by martijn00** [comment]
I've updated it here: https://github.com/Baseflow/Chameleon/commit/2757657a8d192f66a81b16adb6a89209c7910703#diff-4a01a3e06fa219530df030e1f23936faR15
