### ISSUE TITLE
Broken Download Links

### ISSUE THREAD

**Issue by saamerm** [BaseflowIT/Chameleon#12]
## 🐛 Bug Report

README in the Develop branch has broken links for downloading the iOS & Android apps. I tried look for the "Chameleon" app, "BaseflowIT", 
"Martjin00", "Chameleon Media Player" on the iOS & the Android app stores but couldn't find anything there either.

### Expected behavior

Clicking on the "Download" links take you to the Chameleon app in the iOS/Android App Store depending on which icon you click in the README.

### Actual behavior

Clicking on the Android link, takes you to a Android search page, showing "We're sorry, the requested URL was not found on this server." 

Clicking on the iOS link, takes you to the apple.co website. 

### Reproduction steps

On a PC/Mac, click on the Google Play/iTunes download link

### Configuration

**Version:** Developer branch

**Platform:** 
- [ X ] :iphone: iOS
- [ X ] :robot: Android

**Comment by martijn00** [comment]
The apps are in review at the store and links will be available in a couple of days.
